const nodemailer = require('nodemailer');
const logger = require('../utils/logger');

const transporter = nodemailer.createTransport({
    service: 'yahoo',
    auth: {
        user: process.env.YAHOO_EMAIL,
        pass: process.env.YAHOO_APP_PASSWORD
    }
});

/**
 * Send the resilience quiz report to a user via email.
 * @param {string} to - Recipient email address
 * @param {string} name - Recipient name
 * @param {Object} report - Report object containing summary and scores
 */
async function sendQuizReport(to, name, report) {
    const subject = '🌟 Your Resilience Profile from The Resilience Atlas™';

    const html = `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
            <h1 style="color: #2c5f8a;">The Resilience Atlas™</h1>
            <h2>Hello, ${name}! 👋</h2>
            <p>Thank you for completing The Resilience Atlas™ assessment. Here are your results:</p>

            <h3>Overall Resilience Score: <strong>${report.overall}%</strong></h3>
            <p>Your dominant resilience type: <strong>${report.dominantType}</strong></p>

            <h3>Category Breakdown:</h3>
            <ul>
                ${Object.entries(report.categories)
                    .map(([cat, score]) => `<li><strong>${capitalize(cat)}:</strong> ${score}%</li>`)
                    .join('')}
            </ul>

            <h3>Insights:</h3>
            <p>${report.summary}</p>

            <hr/>
            <p style="color: #888; font-size: 12px;">
                This report was generated by The Resilience Atlas™.
                Visit us at <a href="${process.env.APP_URL || 'https://resilience-atlas.app'}">resilience-atlas.app</a>
            </p>
        </div>
    `;

    const mailOptions = {
        from: process.env.YAHOO_EMAIL,
        to,
        subject,
        html
    };

    const info = await transporter.sendMail(mailOptions);
    logger.info(`📧 Quiz report email sent to ${to}: ${info.messageId}`);
    return info;
}

function capitalize(str) {
    return str.charAt(0).toUpperCase() + str.slice(1);
}

module.exports = { sendQuizReport };
