const nodemailer = require('nodemailer');
const logger = require('../utils/logger');

const transporter = nodemailer.createTransport({
    service: 'yahoo',
    auth: {
        user: process.env.YAHOO_EMAIL,
        pass: process.env.YAHOO_APP_PASSWORD
    }
});

/**
 * Send the resilience quiz report to a user via email.
 * @param {string} to - Recipient email address
 * @param {string} name - Recipient name
 * @param {Object} report - Report object containing summary and scores
 */
async function sendQuizReport(to, name, report) {
    const subject = 'Your Resilience Profile from The Resilience Atlas\u2122';

    const html = `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
            <h1 style="color: #2c5f8a;">The Resilience Atlas™</h1>
            <h2>Hello, ${name}!</h2>
            <p>Thank you for completing The Resilience Atlas™ assessment. Here are your results:</p>

            <h3>Overall Resilience Score: <strong>${report.overall}%</strong></h3>
            <p>Your dominant resilience type: <strong>${report.dominantType}</strong></p>

            <h3>Category Breakdown:</h3>
            <ul>
                ${Object.entries(report.categories)
                    .map(([cat, score]) => `<li><strong>${capitalize(cat)}:</strong> ${score}%</li>`)
                    .join('')}
            </ul>

            <h3>Insights:</h3>
            <p>${report.summary}</p>

            <hr/>
            <p style="color: #888; font-size: 12px;">
                This report was generated by The Resilience Atlas™.
                Visit us at <a href="${process.env.APP_URL || 'https://resilience-atlas.app'}">resilience-atlas.app</a>
            </p>
        </div>
    `;

    const mailOptions = {
        from: process.env.YAHOO_EMAIL,
        to,
        subject,
        html
    };

    const info = await transporter.sendMail(mailOptions);
    logger.info(`Quiz report email sent to ${to}: ${info.messageId}`);
    return info;
}

function capitalize(str) {
    return str.charAt(0).toUpperCase() + str.slice(1);
}

/**
 * Send an organization invite email with a join link.
 * @param {string} to - Recipient email address
 * @param {string} orgName - Name of the organization
 * @param {string} joinLink - Full URL to the /join.html page with the invite token
 */
async function sendInviteEmail(to, orgName, joinLink) {
    const subject = `You're invited to join ${orgName} on The Resilience Atlas\u2122`;

    const html = `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
            <h1 style="color: #2c5f8a;">The Resilience Atlas™</h1>
            <h2>You've been invited!</h2>
            <p>You have been invited to join <strong>${orgName}</strong> on The Resilience Atlas™ — a professional resilience assessment platform.</p>
            <p>Click the link below to accept your invitation and complete a team resilience assessment:</p>
            <p style="text-align: center; margin: 2rem 0;">
                <a href="${joinLink}"
                   style="background: #2c5f8a; color: #fff; padding: 12px 28px; border-radius: 6px; text-decoration: none; font-weight: bold; font-size: 16px;">
                    Accept Invitation
                </a>
            </p>
            <p style="color: #666; font-size: 13px;">
                Or copy and paste this link into your browser:<br/>
                <a href="${joinLink}">${joinLink}</a>
            </p>
            <p style="color: #666; font-size: 13px;">This invitation link expires in 7 days.</p>
            <hr/>
            <p style="color: #888; font-size: 12px;">
                This invitation was sent by ${orgName}.
                Visit us at <a href="${process.env.APP_URL || 'https://resilience-atlas.app'}">resilience-atlas.app</a>
            </p>
        </div>
    `;

    const mailOptions = {
        from: process.env.YAHOO_EMAIL,
        to,
        subject,
        html,
    };

    const info = await transporter.sendMail(mailOptions);
    logger.info(`Invite email sent to ${to}: ${info.messageId}`);
    return info;
}

module.exports = { sendQuizReport, sendInviteEmail };
