'use strict';

/**
 * pdfCacheService.js
 *
 * Manages caching of generated PDF reports in MongoDB via the ResilienceReport
 * model.  Caching by resultsHash means users with identical quiz answers share
 * the same cached PDF, eliminating redundant Puppeteer invocations.
 *
 * Cache invalidation strategies
 * ─────────────────────────────
 * 1. TTL / auto-expiry  — 90-day cacheExpiry field; cleanup job deletes stale docs.
 * 2. Version bump       — increment CURRENT_PDF_VERSION to invalidate all cached
 *                         PDFs generated by an older template.
 * 3. Hash-specific      — call invalidateCacheByHash() to invalidate one entry.
 * 4. Full flush         — call invalidateAllCachedPdfs() (admin / emergency).
 */

const crypto = require('crypto');
const ResilienceReport = require('../models/ResilienceReport');

/**
 * Bump this number whenever the PDF template changes.
 * Any cached PDF stored with a lower version is treated as a cache miss.
 */
const CURRENT_PDF_VERSION = 1;

/** How long (in days) a cached PDF is considered valid. */
const CACHE_TTL_DAYS = 90;

/**
 * Sentinel ObjectId used as the userId for cache-only documents that were
 * created by the /api/report/download route before a real user document
 * exists.  Any per-user query MUST exclude this value.
 */
const SENTINEL_USER_ID = '000000000000000000000000';

// ── In-memory metrics (reset on process restart) ──────────────────────────────
let _hits = 0;
let _misses = 0;
let _totalGenerationMs = 0;
let _generationCount = 0;

/**
 * Compute a deterministic SHA-256 hash that uniquely identifies a set of
 * resilience results.  Used as the cache key for the PDF.
 *
 * @param {string|number} overall       – overall score
 * @param {string}        dominantType  – dominant resilience type
 * @param {Object}        scoresObj     – parsed scores object
 * @returns {string} hex digest
 */
function buildResultsHash(overall, dominantType, scoresObj) {
    const payload = JSON.stringify({
        overall: String(overall),
        dominantType: String(dominantType || ''),
        scores: scoresObj,
    });
    return crypto.createHash('sha256').update(payload).digest('hex');
}

/**
 * Look up a valid cached PDF by resultsHash.
 *
 * Returns the PDF `Buffer` when the cache is valid, or `null` on a miss.
 * A hit requires:
 *   - `cached === true`
 *   - `pdfVersion === CURRENT_PDF_VERSION`
 *   - `cacheExpiry` is in the future (or absent)
 *
 * @param {string} resultsHash
 * @returns {Promise<Buffer|null>}
 */
async function getCachedPdf(resultsHash) {
    try {
        const now = new Date();
        const doc = await ResilienceReport.findOne({
            resultsHash,
            cached: true,
            pdfVersion: CURRENT_PDF_VERSION,
            $or: [
                { cacheExpiry: null },
                { cacheExpiry: { $gt: now } },
            ],
        }).select('pdfBuffer pdfGeneratedAt generationTime').lean();

        if (!doc || !doc.pdfBuffer) {
            _misses++;
            return null;
        }

        _hits++;
        return Buffer.from(doc.pdfBuffer, 'base64');
    } catch (err) {
        // Never let a cache error block the user — treat as a miss.
        console.warn('[pdfCacheService] getCachedPdf error (treating as miss):', err.message);
        _misses++;
        return null;
    }
}

/**
 * Store a generated PDF in the cache.
 *
 * Upserts the ResilienceReport document identified by `resultsHash`.
 * When no matching document exists the upsert uses a sentinel userId
 * (`000000000000000000000000`) so the unique index is satisfied; the
 * worker / route that owns the document will overwrite it with the real
 * userId when it persists the full report.  Documents created with the
 * sentinel userId should never be returned in per-user queries — always
 * filter by the real userId when displaying user-owned reports.
 *
 * @param {string} resultsHash    – cache key
 * @param {Buffer} pdfBuffer      – raw PDF binary
 * @param {number} [generationMs] – Puppeteer wall-clock time in ms
 * @returns {Promise<void>}
 */
async function storePdf(resultsHash, pdfBuffer, generationMs) {
    const now = new Date();
    const expiry = new Date(now);
    expiry.setDate(expiry.getDate() + CACHE_TTL_DAYS);

    if (typeof generationMs === 'number') {
        _totalGenerationMs += generationMs;
        _generationCount++;
    }

    try {
        await ResilienceReport.updateOne(
            { resultsHash },
            {
                $set: {
                    pdfBuffer: pdfBuffer.toString('base64'),
                    pdfGeneratedAt: now,
                    pdfVersion: CURRENT_PDF_VERSION,
                    cacheExpiry: expiry,
                    cached: true,
                    generationTime: generationMs ?? null,
                },
                $setOnInsert: {
                    // Satisfy the required userId field for brand-new documents.
                    // Documents with this sentinel userId are cache-only entries
                    // and must be excluded from per-user report queries.
                    userId: SENTINEL_USER_ID,
                    status: 'ready',
                },
            },
            { upsert: true }
        );
    } catch (err) {
        // A caching failure must not surface as a user-facing error.
        console.error('[pdfCacheService] storePdf error (non-fatal):', err.message);
    }
}

/**
 * Invalidate the cached PDF for a specific resultsHash.
 *
 * @param {string} resultsHash
 * @returns {Promise<number>} number of documents updated
 */
async function invalidateCacheByHash(resultsHash) {
    const result = await ResilienceReport.updateMany(
        { resultsHash },
        { $set: { cached: false } }
    );
    return result.modifiedCount;
}

/**
 * Invalidate ALL cached PDFs (e.g. after a major template overhaul).
 * Sets `cached = false` on every document regardless of version.
 *
 * @returns {Promise<number>} number of documents updated
 */
async function invalidateAllCachedPdfs() {
    const result = await ResilienceReport.updateMany(
        { cached: true },
        { $set: { cached: false } }
    );
    return result.modifiedCount;
}

/**
 * Return in-memory cache performance metrics.
 * These counters reset when the Node process restarts.
 *
 * @returns {{ hits: number, misses: number, hitRate: string, avgGenerationMs: string }}
 */
function getCacheStats() {
    const total = _hits + _misses;
    const hitRate = total === 0 ? '0.00' : ((_hits / total) * 100).toFixed(2);
    const avgGenerationMs =
        _generationCount === 0
            ? '0.00'
            : (_totalGenerationMs / _generationCount).toFixed(2);

    return {
        hits: _hits,
        misses: _misses,
        hitRate: `${hitRate}%`,
        avgGenerationMs: `${avgGenerationMs}ms`,
    };
}

/** Reset in-memory metrics (useful in tests). */
function _resetStats() {
    _hits = 0;
    _misses = 0;
    _totalGenerationMs = 0;
    _generationCount = 0;
}

module.exports = {
    CURRENT_PDF_VERSION,
    CACHE_TTL_DAYS,
    SENTINEL_USER_ID,
    buildResultsHash,
    getCachedPdf,
    storePdf,
    invalidateCacheByHash,
    invalidateAllCachedPdfs,
    getCacheStats,
    _resetStats,
};
