# railway.toml

[services]
  [[services]]
    name = "backend"
    root = "."
    build = "npm install"
    start = "node index.js"

  [[services]]
    name = "frontend"
    root = "client"
    build = "npm install && npm run build"
    start = "npm run preview"
