'use strict';

/**
 * resourceSeedData.js — Curated Resource Library Seed Data
 *
 * Evidence-based resources for the Resilience Atlas Resource Library,
 * organized across all seven visible categories and multiple content types.
 *
 * Focus areas: ABA, ACT, Resilience Studies, Cross-Cultural Research,
 *              Psychology, Positive Psychology, Behavioral Science.
 *
 * Source label conventions (in description field):
 *   [Peer-reviewed]   — academic journals / published research
 *   [Gov/Academic]    — government agencies / academic institutions
 *   [Expert-informed] — recognized practitioners / researchers / books
 *
 * Each entry maps directly to the Resource mongoose schema in
 * backend/models/Resource.js.
 */

module.exports = [

  // ══════════════════════════════════════════════════════════════════════════
  // NUTRITION  (7 resources)
  // ══════════════════════════════════════════════════════════════════════════

  {
    title:       'Nutritional Psychiatry: Your Brain on Food',
    type:        'article',
    category:    'nutrition',
    difficulty:  'beginner',
    url:         'https://www.health.harvard.edu/blog/nutritional-psychiatry-your-brain-on-food-201511168626',
    description: 'Harvard Medical School overview of how diet affects mental health, mood, and cognitive function. Reviews evidence for Mediterranean and anti-inflammatory diets in reducing depression and anxiety. [Gov/Academic]',
    excerpt:     'Learn how the food you eat influences brain chemistry, mood, and long-term resilience.',
    authorName:  'Harvard Health Publishing',
    tags:        ['nutrition', 'mental-health', 'brain', 'diet'],
    dimensions:  ['Somatic-Regulative'],
    timeCommitment: 10,
    status:      'published',
    publishedAt: new Date('2023-01-15'),
  },

  {
    title:       'Omega-3 Fatty Acids and Psychiatric Disorders: Evidence Review',
    type:        'article',
    category:    'nutrition',
    difficulty:  'intermediate',
    url:         'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6950146/',
    description: 'Peer-reviewed review published in the NIH National Library of Medicine examining omega-3 supplementation in depression, anxiety, and PTSD. Summarizes randomised controlled trials. [Peer-reviewed]',
    excerpt:     'Systematic review of omega-3 research showing significant effects on mood and stress reactivity.',
    authorName:  'NIH National Library of Medicine',
    tags:        ['omega-3', 'nutrition', 'depression', 'research'],
    dimensions:  ['Somatic-Regulative', 'Emotional-Somatic'],
    timeCommitment: 20,
    status:      'published',
    publishedAt: new Date('2023-02-01'),
  },

  {
    title:       'The Gut-Brain Connection: How Your Diet Affects Mental Health',
    type:        'video',
    category:    'nutrition',
    difficulty:  'beginner',
    url:         'https://www.youtube.com/watch?v=65e2qScV_K8',
    videoProvider: 'youtube',
    videoId:     '65e2qScV_K8',
    description: 'TEDx talk by Dr. Emeran Mayer exploring the science of the gut-brain axis, microbiome research, and how dietary choices shape emotions and resilience. [Expert-informed]',
    excerpt:     'Discover how gut bacteria communicate with your brain and influence emotional wellbeing.',
    authorName:  'TEDx Talks',
    tags:        ['gut-brain', 'microbiome', 'nutrition', 'ted'],
    dimensions:  ['Somatic-Regulative'],
    timeCommitment: 18,
    status:      'published',
    publishedAt: new Date('2023-03-10'),
  },

  {
    title:       'Dietary Guidelines for Americans 2020-2025',
    type:        'pdf',
    category:    'nutrition',
    difficulty:  'beginner',
    url:         'https://www.dietaryguidelines.gov/sites/default/files/2021-03/Dietary_Guidelines_for_Americans-2020-2025.pdf',
    pdfUrl:      'https://www.dietaryguidelines.gov/sites/default/files/2021-03/Dietary_Guidelines_for_Americans-2020-2025.pdf',
    description: 'Official U.S. government dietary guidelines grounded in systematic review of nutrition science. Evidence-based recommendations for healthy eating patterns that support physical and mental health. [Gov/Academic]',
    excerpt:     'Official U.S. dietary guidelines: evidence-based eating patterns for optimal health across the lifespan.',
    authorName:  'USDA and HHS',
    tags:        ['guidelines', 'diet', 'government', 'healthy-eating'],
    dimensions:  ['Somatic-Regulative', 'Agentic-Generative'],
    timeCommitment: 30,
    status:      'published',
    publishedAt: new Date('2023-01-05'),
  },

  {
    title:       'The Nutrition Source Podcast by Harvard',
    type:        'podcast',
    category:    'nutrition',
    difficulty:  'beginner',
    url:         'https://www.hsph.harvard.edu/nutritionsource/2022/01/10/the-nutrition-source-podcast/',
    description: 'Harvard T.H. Chan School of Public Health podcast series covering evidence-based nutrition science, dietary patterns, and how food supports cognitive and emotional resilience. [Gov/Academic]',
    excerpt:     'Harvard nutrition researchers break down the science of healthy eating in plain language.',
    authorName:  'Harvard T.H. Chan School of Public Health',
    tags:        ['podcast', 'harvard', 'nutrition', 'science'],
    dimensions:  ['Somatic-Regulative'],
    timeCommitment: 40,
    status:      'published',
    publishedAt: new Date('2023-04-01'),
  },

  {
    title:       'Assess Your Eating Patterns with USDA MyPlate',
    type:        'quiz',
    category:    'nutrition',
    difficulty:  'beginner',
    url:         'https://www.myplate.gov/myplate-plan',
    description: 'Interactive USDA MyPlate assessment that personalizes dietary recommendations based on age, weight, and activity level. Based on the Dietary Guidelines for Americans. [Gov/Academic]',
    excerpt:     'Get a personalized eating plan from the USDA evidence-based MyPlate tool.',
    authorName:  'USDA MyPlate',
    tags:        ['quiz', 'usda', 'diet', 'self-assessment'],
    dimensions:  ['Agentic-Generative', 'Somatic-Regulative'],
    timeCommitment: 10,
    status:      'published',
    publishedAt: new Date('2023-01-20'),
  },

  {
    title:       'Dr. Uma Naidoo: Nutritional Psychiatry and Food-Mood Science',
    type:        'expert',
    category:    'nutrition',
    difficulty:  'beginner',
    url:         'https://umanaidoomd.com/',
    expertName:  'Dr. Uma Naidoo',
    expertTitle: 'Nutritional Psychiatrist, Harvard Medical School',
    expertBio:   'Dr. Uma Naidoo is a Harvard-trained nutritional psychiatrist, professional chef, and author of "This Is Your Brain on Food." She leads Nutritional and Lifestyle Psychiatry at Massachusetts General Hospital and pioneered the field of nutritional psychiatry.',
    expertContactUrl: 'https://umanaidoomd.com/',
    description: 'World-leading nutritional psychiatrist whose research bridges dietary science and mental health treatment. Author of peer-reviewed articles on food-mood connections. [Expert-informed]',
    excerpt:     'Pioneer of nutritional psychiatry with research on dietary interventions for anxiety, depression, and cognitive function.',
    tags:        ['expert', 'psychiatry', 'nutrition', 'harvard'],
    dimensions:  ['Somatic-Regulative', 'Emotional-Somatic'],
    timeCommitment: 5,
    status:      'published',
    publishedAt: new Date('2023-01-10'),
  },

  // ══════════════════════════════════════════════════════════════════════════
  // EXERCISE  (7 resources)
  // ══════════════════════════════════════════════════════════════════════════

  {
    title:       'Physical Activity and Mental Health: CDC Overview',
    type:        'article',
    category:    'exercise',
    difficulty:  'beginner',
    url:         'https://www.cdc.gov/physicalactivity/basics/pa-health/index.htm',
    description: 'CDC evidence review of physical activity\'s impact on depression, anxiety, stress, and cognitive resilience. Covers recommended activity levels and their psychological benefits. [Gov/Academic]',
    excerpt:     'CDC overview of how regular physical activity reduces anxiety, depression, and improves mental health.',
    authorName:  'Centers for Disease Control and Prevention',
    tags:        ['exercise', 'mental-health', 'cdc', 'guidelines'],
    dimensions:  ['Somatic-Regulative', 'Agentic-Generative'],
    timeCommitment: 10,
    status:      'published',
    publishedAt: new Date('2023-01-15'),
  },

  {
    title:       'Dr. John J. Ratey: Exercise and Brain Science',
    type:        'expert',
    category:    'exercise',
    difficulty:  'intermediate',
    url:         'https://www.johnjratey.com/spark',
    expertName:  'Dr. John J. Ratey',
    expertTitle: 'Associate Clinical Professor of Psychiatry, Harvard Medical School',
    expertBio:   'Dr. John Ratey is a Harvard psychiatrist and internationally recognized authority on the brain-fitness connection. His book "Spark" synthesises decades of neuroscience research showing how aerobic exercise transforms the brain and builds stress resilience.',
    expertContactUrl: 'https://www.johnjratey.com/',
    description: 'Harvard psychiatrist whose landmark synthesis of peer-reviewed neuroscience on exercise and brain function demonstrates how aerobic activity builds BDNF, reduces anxiety, and supports resilience. [Expert-informed]',
    excerpt:     'Harvard psychiatrist reveals how exercise is the single best tool for optimizing brain performance and resilience.',
    tags:        ['expert', 'harvard', 'exercise', 'neuroscience', 'brain'],
    dimensions:  ['Somatic-Regulative', 'Cognitive-Narrative', 'Agentic-Generative'],
    timeCommitment: 5,
    status:      'published',
    publishedAt: new Date('2023-02-01'),
  },

  {
    title:       'Exercise as a Stress Buffer: APA Research Summary',
    type:        'article',
    category:    'exercise',
    difficulty:  'intermediate',
    url:         'https://www.apa.org/topics/exercise-fitness/stress',
    description: 'APA overview of how regular exercise modulates the stress response, HPA axis reactivity, and builds psychological resilience. Covers both aerobic and resistance training evidence. [Gov/Academic]',
    excerpt:     'APA explains how exercise reshapes stress-response systems, building long-term psychological resilience.',
    authorName:  'American Psychological Association',
    tags:        ['apa', 'exercise', 'stress', 'resilience'],
    dimensions:  ['Somatic-Regulative', 'Emotional-Somatic'],
    timeCommitment: 12,
    status:      'published',
    publishedAt: new Date('2023-02-15'),
  },

  {
    title:       'The Neuroscience of Exercise: Wendy Suzuki TED Talk',
    type:        'video',
    category:    'exercise',
    difficulty:  'beginner',
    url:         'https://www.youtube.com/watch?v=BHY0FxzoKZE',
    videoProvider: 'youtube',
    videoId:     'BHY0FxzoKZE',
    description: 'Neuroscientist Wendy Suzuki\'s widely viewed TED Talk on how aerobic exercise changes the brain, protects against neurodegenerative disease, and builds resilience against anxiety and depression. [Expert-informed]',
    excerpt:     'Neuroscientist Wendy Suzuki explains the brain-altering effects of exercise, with practical implications for resilience.',
    authorName:  'TED',
    tags:        ['ted', 'neuroscience', 'exercise', 'brain'],
    dimensions:  ['Somatic-Regulative', 'Cognitive-Narrative'],
    timeCommitment: 13,
    status:      'published',
    publishedAt: new Date('2023-03-01'),
  },

  {
    title:       'Physical Activity Guidelines for Americans, 2nd Edition',
    type:        'pdf',
    category:    'exercise',
    difficulty:  'beginner',
    url:         'https://health.gov/sites/default/files/2019-09/Physical_Activity_Guidelines_2nd_edition.pdf',
    pdfUrl:      'https://health.gov/sites/default/files/2019-09/Physical_Activity_Guidelines_2nd_edition.pdf',
    description: 'Comprehensive U.S. HHS evidence-based guidelines for physical activity across all age groups. Includes mental health benefits, frequency and intensity recommendations. [Gov/Academic]',
    excerpt:     'Official U.S. physical activity guidelines with evidence-based recommendations for health across the lifespan.',
    authorName:  'U.S. Department of Health and Human Services',
    tags:        ['guidelines', 'exercise', 'hhs', 'activity'],
    dimensions:  ['Somatic-Regulative', 'Agentic-Generative'],
    timeCommitment: 25,
    status:      'published',
    publishedAt: new Date('2023-01-08'),
  },

  {
    title:       'Science of Exercise: University of Colorado Free Course',
    type:        'podcast',
    category:    'exercise',
    difficulty:  'intermediate',
    url:         'https://www.coursera.org/learn/science-exercise',
    description: 'Free online course from University of Colorado covering exercise physiology, the science of fitness, mental health benefits of physical activity, and evidence-based training principles. [Gov/Academic]',
    excerpt:     'University of Colorado course explaining the science behind how exercise transforms body and mind.',
    authorName:  'University of Colorado Boulder',
    tags:        ['course', 'exercise', 'physiology', 'science'],
    dimensions:  ['Somatic-Regulative', 'Agentic-Generative'],
    timeCommitment: 180,
    status:      'published',
    publishedAt: new Date('2023-03-20'),
  },

  {
    title:       'Exercise Readiness and Fitness Assessment: ACE Calculators',
    type:        'quiz',
    category:    'exercise',
    difficulty:  'beginner',
    url:         'https://www.acefitness.org/resources/everyone/blog/fitness-calculators/',
    description: 'American Council on Exercise (ACE) evidence-based fitness assessment tools including physical activity readiness, target heart rate, and BMI calculators to personalize exercise programs. [Expert-informed]',
    excerpt:     'ACE fitness assessment tools to help you find the right exercise intensity and type for your health goals.',
    authorName:  'American Council on Exercise',
    tags:        ['quiz', 'fitness', 'ace', 'self-assessment'],
    dimensions:  ['Somatic-Regulative', 'Agentic-Generative'],
    timeCommitment: 10,
    status:      'published',
    publishedAt: new Date('2023-02-10'),
  },

  // ══════════════════════════════════════════════════════════════════════════
  // MEDITATION  (7 resources)
  // ══════════════════════════════════════════════════════════════════════════

  {
    title:       'Mindfulness-Based Stress Reduction: The Evidence Base',
    type:        'article',
    category:    'meditation',
    difficulty:  'beginner',
    url:         'https://www.apa.org/monitor/2019/10/cover-mindfulness-therapy',
    description: 'APA Monitor feature reviewing 40+ years of MBSR research developed by Jon Kabat-Zinn at UMass. Summarizes meta-analyses on mindfulness efficacy for stress, anxiety, depression, and chronic pain. [Gov/Academic]',
    excerpt:     'APA review of four decades of mindfulness-based stress reduction research and its proven benefits.',
    authorName:  'American Psychological Association',
    tags:        ['mindfulness', 'mbsr', 'apa', 'stress-reduction'],
    dimensions:  ['Somatic-Regulative', 'Emotional-Somatic', 'Cognitive-Narrative'],
    timeCommitment: 15,
    status:      'published',
    publishedAt: new Date('2023-01-20'),
  },

  {
    title:       'ACT and Mindfulness: Introduction to Acceptance and Commitment Therapy',
    type:        'article',
    category:    'meditation',
    difficulty:  'intermediate',
    url:         'https://contextualscience.org/act',
    description: 'Association for Contextual Behavioral Science overview of ACT, the evidence-based therapeutic approach integrating mindfulness, values, and psychological flexibility. Over 500 randomised controlled trials support ACT effectiveness. [Peer-reviewed]',
    excerpt:     'Introduction to ACT: the evidence-based approach combining mindfulness and values-based action backed by 500+ RCTs.',
    authorName:  'Association for Contextual Behavioral Science',
    tags:        ['act', 'mindfulness', 'acceptance', 'psychological-flexibility'],
    dimensions:  ['Cognitive-Narrative', 'Emotional-Somatic', 'Agentic-Generative'],
    timeCommitment: 15,
    status:      'published',
    publishedAt: new Date('2023-02-05'),
  },

  {
    title:       'Guided Body Scan Meditation with Jon Kabat-Zinn',
    type:        'video',
    category:    'meditation',
    difficulty:  'beginner',
    url:         'https://www.youtube.com/watch?v=_DTmGtznab4',
    videoProvider: 'youtube',
    videoId:     '_DTmGtznab4',
    description: 'Body scan and mindfulness meditation guided by Jon Kabat-Zinn, founder of Mindfulness-Based Stress Reduction. Suitable for beginners, drawn from the evidence-based MBSR protocol. [Expert-informed]',
    excerpt:     'A guided body-scan meditation from the founder of MBSR: a great starting point for evidence-based mindfulness practice.',
    authorName:  'Jon Kabat-Zinn',
    tags:        ['guided-meditation', 'mbsr', 'body-scan', 'beginner'],
    dimensions:  ['Somatic-Regulative', 'Emotional-Somatic'],
    timeCommitment: 32,
    status:      'published',
    publishedAt: new Date('2023-03-05'),
  },

  {
    title:       'Dr. Steven C. Hayes: ACT and Psychological Flexibility',
    type:        'expert',
    category:    'meditation',
    difficulty:  'intermediate',
    url:         'https://stevenchayes.com/',
    expertName:  'Dr. Steven C. Hayes',
    expertTitle: 'Nevada Foundation Professor of Psychology, University of Nevada; Founder of ACT',
    expertBio:   'Dr. Steven Hayes is the originator of Acceptance and Commitment Therapy (ACT) and Relational Frame Theory (RFT). He has authored over 600 scientific articles and 46 books. ACT has more than 500 randomised controlled trials demonstrating its efficacy across anxiety, depression, PTSD, and resilience-building.',
    expertContactUrl: 'https://stevenchayes.com/',
    description: 'Originator of ACT and world leader in contextual behavioral science. His work on psychological flexibility underpins resilience research globally. [Expert-informed]',
    excerpt:     'Founder of Acceptance and Commitment Therapy: the evidence-based approach that transformed how we build psychological resilience.',
    tags:        ['act', 'expert', 'psychology', 'acceptance', 'resilience'],
    dimensions:  ['Cognitive-Narrative', 'Emotional-Somatic', 'Agentic-Generative', 'Spiritual-Reflective'],
    timeCommitment: 5,
    status:      'published',
    publishedAt: new Date('2023-01-10'),
  },

  {
    title:       'The Mindfulness and Acceptance Workbook for Anxiety',
    type:        'pdf',
    category:    'meditation',
    difficulty:  'intermediate',
    url:         'https://www.newharbinger.com/9781572244993/the-mindfulness-and-acceptance-workbook-for-anxiety/',
    pdfUrl:      'https://www.newharbinger.com/9781572244993/the-mindfulness-and-acceptance-workbook-for-anxiety/',
    description: 'Companion workbook to evidence-based ACT treatment for anxiety, developed by researchers at University of Nevada. Includes mindfulness exercises, values clarification, and defusion techniques backed by clinical research. [Peer-reviewed]',
    excerpt:     'Evidence-based ACT workbook for reducing anxiety through mindfulness, acceptance, and values-aligned action.',
    authorName:  'John P. Forsyth and Georg H. Eifert',
    tags:        ['act', 'workbook', 'anxiety', 'mindfulness'],
    dimensions:  ['Cognitive-Narrative', 'Emotional-Somatic', 'Agentic-Generative'],
    timeCommitment: 120,
    status:      'published',
    publishedAt: new Date('2023-02-20'),
  },

  {
    title:       'Ten Percent Happier Podcast: Science of Meditation',
    type:        'podcast',
    category:    'meditation',
    difficulty:  'beginner',
    url:         'https://www.tenpercent.com/podcast',
    description: 'Award-winning podcast by Dan Harris featuring interviews with neuroscientists, psychologists, and meditation teachers. Episodes regularly cover research on mindfulness, ACT, and stress resilience. [Expert-informed]',
    excerpt:     'Interviews with leading scientists and teachers on the evidence-based benefits of meditation and mindfulness.',
    authorName:  'Dan Harris / Ten Percent Happier',
    tags:        ['podcast', 'meditation', 'mindfulness', 'science'],
    dimensions:  ['Emotional-Somatic', 'Cognitive-Narrative'],
    timeCommitment: 60,
    status:      'published',
    publishedAt: new Date('2023-04-01'),
  },

  {
    title:       'Five Facets of Mindfulness Questionnaire',
    type:        'quiz',
    category:    'meditation',
    difficulty:  'beginner',
    url:         'https://www.psytoolkit.org/survey-library/mindfulness-ffmq.html',
    description: 'Validated 39-item self-report questionnaire developed by Baer et al. (2006) measuring five dimensions of mindfulness: observing, describing, acting with awareness, non-judging, and non-reactivity. Widely used in mindfulness research. [Peer-reviewed]',
    excerpt:     'Scientifically validated tool to measure your current level of mindfulness across five key dimensions.',
    authorName:  'Baer et al., University of Kentucky',
    tags:        ['quiz', 'mindfulness', 'ffmq', 'validated'],
    dimensions:  ['Cognitive-Narrative', 'Emotional-Somatic', 'Somatic-Regulative'],
    timeCommitment: 15,
    status:      'published',
    publishedAt: new Date('2023-03-15'),
  },

  // ══════════════════════════════════════════════════════════════════════════
  // SLEEP  (7 resources)
  // ══════════════════════════════════════════════════════════════════════════

  {
    title:       'Dr. Matthew Walker: The Science of Sleep and Resilience',
    type:        'expert',
    category:    'sleep',
    difficulty:  'beginner',
    url:         'https://www.sleepdiplomat.com/',
    expertName:  'Dr. Matthew Walker',
    expertTitle: 'Professor of Neuroscience and Psychology, University of California Berkeley',
    expertBio:   'Dr. Matthew Walker is a world-renowned sleep scientist and author of the New York Times bestseller "Why We Sleep." His research at the Sleep and Neuroimaging Lab at UC Berkeley has transformed our understanding of sleep\'s role in mental health, emotional regulation, and resilience.',
    expertContactUrl: 'https://www.sleepdiplomat.com/',
    description: 'Leading sleep scientist whose research definitively establishes the role of sleep in emotional resilience, memory consolidation, and mental health. Author of the landmark book "Why We Sleep." [Expert-informed]',
    excerpt:     'World\'s leading sleep scientist explains how sleep is the single most important pillar of physical and mental health.',
    tags:        ['expert', 'sleep', 'neuroscience', 'brain'],
    dimensions:  ['Somatic-Regulative', 'Emotional-Somatic', 'Cognitive-Narrative'],
    timeCommitment: 5,
    status:      'published',
    publishedAt: new Date('2023-01-12'),
  },

  {
    title:       'Sleep and Mental Health: Harvard Health Overview',
    type:        'article',
    category:    'sleep',
    difficulty:  'beginner',
    url:         'https://www.health.harvard.edu/newsletter_article/sleep-and-mental-health',
    description: 'Harvard Medical School evidence review of bidirectional relationship between sleep quality and mental health. Covers insomnia, depression, anxiety, and resilience implications with practical intervention recommendations. [Gov/Academic]',
    excerpt:     'Harvard Medical School on the powerful two-way relationship between sleep quality and mental health.',
    authorName:  'Harvard Health Publishing',
    tags:        ['sleep', 'mental-health', 'harvard', 'insomnia'],
    dimensions:  ['Somatic-Regulative', 'Emotional-Somatic'],
    timeCommitment: 10,
    status:      'published',
    publishedAt: new Date('2023-02-08'),
  },

  {
    title:       'Sleep Deprivation and Deficiency: NIH Health Guide',
    type:        'article',
    category:    'sleep',
    difficulty:  'beginner',
    url:         'https://www.nhlbi.nih.gov/health/sleep-deprivation',
    description: 'National Heart, Lung, and Blood Institute (NIH) comprehensive guide on sleep deprivation: causes, effects on brain function, emotional regulation, and evidence-based strategies for improving sleep quality. [Gov/Academic]',
    excerpt:     'NIH comprehensive overview of sleep deprivation\'s impact on brain function, emotions, and how to address it.',
    authorName:  'National Heart, Lung, and Blood Institute',
    tags:        ['sleep', 'nih', 'deprivation', 'health'],
    dimensions:  ['Somatic-Regulative'],
    timeCommitment: 12,
    status:      'published',
    publishedAt: new Date('2023-01-25'),
  },

  {
    title:       'Sleep Is Your Superpower: Matt Walker TED Talk',
    type:        'video',
    category:    'sleep',
    difficulty:  'beginner',
    url:         'https://www.youtube.com/watch?v=5MuIMqhT8DM',
    videoProvider: 'youtube',
    videoId:     '5MuIMqhT8DM',
    description: 'Dr. Matthew Walker\'s landmark TED Talk viewed over 15 million times. Covers sleep science research showing sleep\'s critical role in learning, emotional resilience, immune function, and mental health. [Expert-informed]',
    excerpt:     'The world\'s most-watched sleep science talk: why sleep is the greatest legal performance-enhancing tool.',
    authorName:  'TED / Dr. Matthew Walker',
    tags:        ['ted', 'sleep', 'neuroscience', 'health'],
    dimensions:  ['Somatic-Regulative', 'Cognitive-Narrative'],
    timeCommitment: 19,
    status:      'published',
    publishedAt: new Date('2023-03-01'),
  },

  {
    title:       'Cognitive Behavioral Therapy for Insomnia (CBT-I) Self-Help Workbook',
    type:        'pdf',
    category:    'sleep',
    difficulty:  'intermediate',
    url:         'https://www.va.gov/WHOLEHEALTHLIBRARY/tools/cognitive-behavioral-therapy-for-insomnia.asp',
    pdfUrl:      'https://www.va.gov/WHOLEHEALTHLIBRARY/tools/cognitive-behavioral-therapy-for-insomnia.asp',
    description: 'Evidence-based CBT-I self-help workbook from the U.S. Department of Veterans Affairs. CBT-I is the first-line recommended treatment for chronic insomnia by the American College of Physicians and American Academy of Sleep Medicine. [Gov/Academic]',
    excerpt:     'Clinician-developed CBT-I workbook from the VA: the gold-standard treatment for insomnia backed by 50+ clinical trials.',
    authorName:  'U.S. Department of Veterans Affairs',
    tags:        ['cbt-i', 'insomnia', 'workbook', 'therapy'],
    dimensions:  ['Somatic-Regulative', 'Cognitive-Narrative'],
    timeCommitment: 60,
    status:      'published',
    publishedAt: new Date('2023-02-15'),
  },

  {
    title:       'The Matt Walker Podcast: Deep Dive into Sleep Science',
    type:        'podcast',
    category:    'sleep',
    difficulty:  'beginner',
    url:         'https://www.sleepdiplomat.com/podcast',
    description: 'Podcast by UC Berkeley sleep scientist Dr. Matthew Walker covering deep-dive episodes on sleep science, emotional regulation, dreams, and practical sleep improvement strategies drawn from peer-reviewed research. [Expert-informed]',
    excerpt:     'UC Berkeley sleep scientist\'s podcast covering the latest science on sleep, dreams, and resilience.',
    authorName:  'Dr. Matthew Walker',
    tags:        ['podcast', 'sleep', 'science', 'neuroscience'],
    dimensions:  ['Somatic-Regulative', 'Emotional-Somatic'],
    timeCommitment: 45,
    status:      'published',
    publishedAt: new Date('2023-04-10'),
  },

  {
    title:       'Pittsburgh Sleep Quality Index: Validated Sleep Assessment',
    type:        'quiz',
    category:    'sleep',
    difficulty:  'beginner',
    url:         'https://www.sleep.pitt.edu/wp-content/uploads/2020/03/The-PSQI.pdf',
    description: 'Validated 19-item self-report questionnaire developed at the University of Pittsburgh. The PSQI is the gold-standard research tool for assessing sleep quality and disturbances. Published in Sleep journal (Buysse et al., 1989). [Peer-reviewed]',
    excerpt:     'The gold-standard, validated research tool for assessing your sleep quality across seven key dimensions.',
    authorName:  'Buysse et al., University of Pittsburgh',
    tags:        ['quiz', 'sleep', 'psqi', 'validated'],
    dimensions:  ['Somatic-Regulative'],
    timeCommitment: 10,
    status:      'published',
    publishedAt: new Date('2023-03-10'),
  },

  // ══════════════════════════════════════════════════════════════════════════
  // RELATIONSHIPS  (7 resources)
  // ══════════════════════════════════════════════════════════════════════════

  {
    title:       'The Power of Vulnerability: Brene Brown TED Talk',
    type:        'video',
    category:    'relationships',
    difficulty:  'beginner',
    url:         'https://www.youtube.com/watch?v=iCvmsMzlF7o',
    videoProvider: 'youtube',
    videoId:     'iCvmsMzlF7o',
    description: 'Dr. Brene Brown\'s landmark TED Talk on vulnerability, shame, and authentic human connection. Based on qualitative research with thousands of participants. One of the most-watched TED Talks of all time. [Expert-informed]',
    excerpt:     'Groundbreaking research on how vulnerability and authentic connection are foundations of resilience and belonging.',
    authorName:  'TED / Dr. Brene Brown',
    tags:        ['ted', 'vulnerability', 'connection', 'resilience'],
    dimensions:  ['Relational-Social', 'Emotional-Somatic'],
    timeCommitment: 20,
    status:      'published',
    publishedAt: new Date('2023-01-25'),
  },

  {
    title:       'Social Support and Resilience: APA Research Summary',
    type:        'article',
    category:    'relationships',
    difficulty:  'beginner',
    url:         'https://www.apa.org/topics/resilience',
    description: 'American Psychological Association comprehensive overview of research on resilience, with strong emphasis on social support as the most consistently identified resilience factor across populations and cultures. [Gov/Academic]',
    excerpt:     'APA overview showing social connectedness as the most reliable predictor of resilience across all research populations.',
    authorName:  'American Psychological Association',
    tags:        ['apa', 'resilience', 'social-support', 'relationships'],
    dimensions:  ['Relational-Social'],
    timeCommitment: 12,
    status:      'published',
    publishedAt: new Date('2023-02-01'),
  },

  {
    title:       'Dr. John Gottman: The Science of Relationships',
    type:        'expert',
    category:    'relationships',
    difficulty:  'intermediate',
    url:         'https://www.gottman.com/',
    expertName:  'Dr. John Gottman',
    expertTitle: 'Professor Emeritus of Psychology, University of Washington',
    expertBio:   'Dr. John Gottman is a leading relationship researcher who has studied couples for over 40 years. His research including the "Love Lab" longitudinal studies has identified evidence-based predictors of relationship stability and communication patterns that build relational resilience. He is author of over 200 published academic articles.',
    expertContactUrl: 'https://www.gottman.com/',
    description: 'World\'s most published relationship researcher. Gottman\'s longitudinal studies identified evidence-based predictors of relationship success and built interventions used in couples therapy globally. [Expert-informed]',
    excerpt:     'Pioneer relationship researcher whose 40+ years of longitudinal data identified the science of lasting, resilient relationships.',
    tags:        ['expert', 'relationships', 'psychology', 'gottman'],
    dimensions:  ['Relational-Social'],
    timeCommitment: 5,
    status:      'published',
    publishedAt: new Date('2023-01-10'),
  },

  {
    title:       'Cross-Cultural Perspectives on Social Resilience',
    type:        'article',
    category:    'relationships',
    difficulty:  'advanced',
    url:         'https://www.apa.org/pubs/journals/features/amp-amp0000192.pdf',
    description: 'Peer-reviewed APA article examining how cultural contexts shape social support systems and relational resilience. Reviews cross-cultural differences in social ties, collectivism vs. individualism, and resilience outcomes across diverse populations. [Peer-reviewed]',
    excerpt:     'Peer-reviewed review of how cultural context shapes social support systems and relational resilience outcomes.',
    authorName:  'American Psychological Association',
    tags:        ['cross-cultural', 'resilience', 'social', 'peer-reviewed'],
    dimensions:  ['Relational-Social', 'Cognitive-Narrative'],
    timeCommitment: 25,
    status:      'published',
    publishedAt: new Date('2023-03-01'),
  },

  {
    title:       'DBT Interpersonal Effectiveness Skills Workbook',
    type:        'pdf',
    category:    'relationships',
    difficulty:  'intermediate',
    url:         'https://www.dbtselfhelp.com/html/ie_overview.html',
    pdfUrl:      'https://www.dbtselfhelp.com/html/ie_overview.html',
    description: 'Dialectical Behavior Therapy (DBT) interpersonal effectiveness module based on Marsha Linehan\'s evidence-based skills training. Covers DEAR MAN, GIVE, and FAST skills for building healthy, resilient relationships. [Peer-reviewed]',
    excerpt:     'Evidence-based DBT skills workbook for building healthy communication, assertiveness, and relationship resilience.',
    authorName:  'DBT Self Help (based on Linehan, 1993)',
    tags:        ['dbt', 'workbook', 'skills', 'relationships'],
    dimensions:  ['Relational-Social', 'Emotional-Somatic'],
    timeCommitment: 90,
    status:      'published',
    publishedAt: new Date('2023-02-20'),
  },

  {
    title:       'Unlocking Us with Brene Brown: Research on Connection',
    type:        'podcast',
    category:    'relationships',
    difficulty:  'beginner',
    url:         'https://brenebrown.com/podcast/introducing-unlocking-us/',
    description: 'Award-winning podcast by Dr. Brene Brown, researcher and professor at the University of Houston, exploring the human experience of connection, belonging, vulnerability, and relational resilience. Frequently features peer-reviewed research. [Expert-informed]',
    excerpt:     'Brene Brown\'s research-informed podcast on vulnerability, shame, courage, and the power of human connection.',
    authorName:  'Brene Brown',
    tags:        ['podcast', 'relationships', 'vulnerability', 'brene-brown'],
    dimensions:  ['Relational-Social', 'Emotional-Somatic'],
    timeCommitment: 60,
    status:      'published',
    publishedAt: new Date('2023-04-05'),
  },

  {
    title:       'UCLA Loneliness Scale: Social Connectedness Self-Assessment',
    type:        'quiz',
    category:    'relationships',
    difficulty:  'beginner',
    url:         'https://www.psytoolkit.org/survey-library/loneliness-UCLA.html',
    description: 'Validated 20-item UCLA Loneliness Scale (Russell, 1996) measuring perceived social isolation and quality of social connections. Used in hundreds of peer-reviewed studies. [Peer-reviewed]',
    excerpt:     'Validated research tool to measure your sense of social connectedness and identify areas for relationship growth.',
    authorName:  'Russell, D.W. (1996), University of California Los Angeles',
    tags:        ['quiz', 'loneliness', 'validated', 'social'],
    dimensions:  ['Relational-Social'],
    timeCommitment: 10,
    status:      'published',
    publishedAt: new Date('2023-03-05'),
  },

  // ══════════════════════════════════════════════════════════════════════════
  // CAREER  (7 resources)
  // ══════════════════════════════════════════════════════════════════════════

  {
    title:       'Grit: The Power of Passion and Perseverance — Angela Duckworth TED',
    type:        'video',
    category:    'career',
    difficulty:  'beginner',
    url:         'https://www.youtube.com/watch?v=H14bBuluwB8',
    videoProvider: 'youtube',
    videoId:     'H14bBuluwB8',
    description: 'Psychologist Angela Duckworth\'s landmark TED Talk on grit as a predictor of long-term career success. Based on longitudinal studies in education, military, and professional settings. One of the most-watched TED Talks ever. [Expert-informed]',
    excerpt:     'Psychologist Angela Duckworth on why passion and perseverance, not talent, predict career resilience and success.',
    authorName:  'TED / Angela Duckworth',
    tags:        ['ted', 'grit', 'career', 'perseverance'],
    dimensions:  ['Agentic-Generative', 'Cognitive-Narrative'],
    timeCommitment: 6,
    status:      'published',
    publishedAt: new Date('2023-01-30'),
  },

  {
    title:       'Psychological Flexibility in the Workplace: ACT at Work',
    type:        'article',
    category:    'career',
    difficulty:  'intermediate',
    url:         'https://contextualscience.org/act_in_the_workplace',
    description: 'Association for Contextual Behavioral Science review of ACT applications in workplace settings. Covers research on psychological flexibility, values-based action, and acceptance as predictors of occupational resilience and wellbeing. [Peer-reviewed]',
    excerpt:     'How ACT\'s psychological flexibility model predicts career resilience, burnout prevention, and professional wellbeing.',
    authorName:  'Association for Contextual Behavioral Science',
    tags:        ['act', 'workplace', 'resilience', 'career'],
    dimensions:  ['Agentic-Generative', 'Cognitive-Narrative', 'Emotional-Somatic'],
    timeCommitment: 15,
    status:      'published',
    publishedAt: new Date('2023-02-10'),
  },

  {
    title:       'Dr. Angela Duckworth: Grit and Character Science',
    type:        'expert',
    category:    'career',
    difficulty:  'intermediate',
    url:         'https://angeladuckworth.com/',
    expertName:  'Dr. Angela Duckworth',
    expertTitle: 'Professor of Psychology, University of Pennsylvania; Founder, Character Lab',
    expertBio:   'Dr. Angela Duckworth is a pioneering researcher on grit, self-control, and character development. She founded the Character Lab and is author of the bestselling book "Grit: The Power of Passion and Perseverance." Her longitudinal research across diverse populations has redefined how we understand career resilience and achievement.',
    expertContactUrl: 'https://angeladuckworth.com/',
    description: 'MacArthur Fellowship-winning psychologist whose longitudinal research on grit and perseverance has transformed our understanding of career resilience and long-term achievement. [Expert-informed]',
    excerpt:     'MacArthur "genius grant" winner whose research proves that grit, not talent, is the key predictor of career success.',
    tags:        ['expert', 'grit', 'psychology', 'career', 'resilience'],
    dimensions:  ['Agentic-Generative', 'Cognitive-Narrative'],
    timeCommitment: 5,
    status:      'published',
    publishedAt: new Date('2023-01-15'),
  },

  {
    title:       'Post-Traumatic Growth at Work: APA Research',
    type:        'article',
    category:    'career',
    difficulty:  'intermediate',
    url:         'https://www.apa.org/monitor/2016/11/growth-adversity',
    description: 'APA Monitor article on post-traumatic growth theory and its application to workplace resilience, career setbacks, and professional transformation after adversity. Reviews Tedeschi and Calhoun foundational PTG research. [Gov/Academic]',
    excerpt:     'APA research on post-traumatic growth: how career adversity can become a launching pad for deeper purpose and resilience.',
    authorName:  'American Psychological Association',
    tags:        ['ptg', 'career', 'resilience', 'growth'],
    dimensions:  ['Agentic-Generative', 'Cognitive-Narrative', 'Spiritual-Reflective'],
    timeCommitment: 15,
    status:      'published',
    publishedAt: new Date('2023-02-25'),
  },

  {
    title:       'Career Resilience: Thriving Through Change Guide',
    type:        'pdf',
    category:    'career',
    difficulty:  'intermediate',
    url:         'https://www.mindtools.com/pages/article/career-resilience.htm',
    pdfUrl:      'https://www.mindtools.com/pages/article/career-resilience.htm',
    description: 'Evidence-informed career resilience framework covering adaptability, professional identity, growth mindset, and values-based goal setting. Based on positive psychology and ACT principles for navigating career transitions. [Expert-informed]',
    excerpt:     'Evidence-informed guide for building career resilience using positive psychology and ACT frameworks.',
    authorName:  'Mind Tools',
    tags:        ['workbook', 'career', 'resilience', 'adaptability'],
    dimensions:  ['Agentic-Generative', 'Cognitive-Narrative'],
    timeCommitment: 45,
    status:      'published',
    publishedAt: new Date('2023-03-15'),
  },

  {
    title:       'WorkLife with Adam Grant: Work Psychology Podcast',
    type:        'podcast',
    category:    'career',
    difficulty:  'beginner',
    url:         'https://www.adamgrant.net/podcast/',
    description: 'Podcast by Wharton psychologist and bestselling author Adam Grant exploring the science of work, creativity, motivation, and career resilience. Episodes synthesise peer-reviewed research with real-world examples. [Expert-informed]',
    excerpt:     'Wharton psychologist Adam Grant explores the science behind meaningful work, resilience, and professional growth.',
    authorName:  'Adam Grant / TED',
    tags:        ['podcast', 'work', 'psychology', 'career'],
    dimensions:  ['Agentic-Generative', 'Relational-Social'],
    timeCommitment: 60,
    status:      'published',
    publishedAt: new Date('2023-04-01'),
  },

  {
    title:       'Grit Scale Self-Assessment by Angela Duckworth',
    type:        'quiz',
    category:    'career',
    difficulty:  'beginner',
    url:         'https://angeladuckworth.com/grit-scale/',
    description: 'The validated 10-item Grit Scale developed by Dr. Angela Duckworth at the University of Pennsylvania. Measures consistency of interest and perseverance of effort, both predictors of long-term career resilience. Used in hundreds of peer-reviewed studies. [Peer-reviewed]',
    excerpt:     'Validated 10-item self-assessment to measure your level of grit: the key predictor of career resilience and achievement.',
    authorName:  'Angela Duckworth, University of Pennsylvania',
    tags:        ['quiz', 'grit', 'validated', 'career'],
    dimensions:  ['Agentic-Generative'],
    timeCommitment: 5,
    status:      'published',
    publishedAt: new Date('2023-03-01'),
  },

  // ══════════════════════════════════════════════════════════════════════════
  // GENERAL  (8 resources)
  // ══════════════════════════════════════════════════════════════════════════

  {
    title:       'Building Your Resilience: APA Evidence-Based Guide',
    type:        'article',
    category:    'general',
    difficulty:  'beginner',
    url:         'https://www.apa.org/topics/resilience/building-your-resilience',
    description: 'American Psychological Association foundational guide to resilience research: what resilience is, 10 evidence-based strategies for building it, and how to apply them in daily life. Draws on decades of resilience science. [Gov/Academic]',
    excerpt:     'APA\'s definitive guide to building resilience: 10 evidence-based strategies drawn from decades of research.',
    authorName:  'American Psychological Association',
    tags:        ['apa', 'resilience', 'strategies', 'evidence-based'],
    dimensions:  ['Cognitive-Narrative', 'Emotional-Somatic', 'Relational-Social', 'Agentic-Generative'],
    timeCommitment: 15,
    status:      'published',
    publishedAt: new Date('2023-01-05'),
  },

  {
    title:       'Resilience Across Cultures: A Systematic Review',
    type:        'article',
    category:    'general',
    difficulty:  'advanced',
    url:         'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5839676/',
    description: 'Peer-reviewed systematic review in the National Library of Medicine examining resilience research across diverse cultural contexts. Identifies universal and culturally-specific resilience factors and challenges Western-centric models. [Peer-reviewed]',
    excerpt:     'Peer-reviewed systematic review challenging Western-centric resilience models with cross-cultural evidence from diverse populations.',
    authorName:  'NIH National Library of Medicine',
    tags:        ['cross-cultural', 'resilience', 'systematic-review', 'peer-reviewed'],
    dimensions:  ['Cognitive-Narrative', 'Relational-Social', 'Spiritual-Reflective'],
    timeCommitment: 30,
    status:      'published',
    publishedAt: new Date('2023-02-15'),
  },

  {
    title:       'Dr. Martin Seligman: Positive Psychology and PERMA Wellbeing',
    type:        'expert',
    category:    'general',
    difficulty:  'beginner',
    url:         'https://ppc.sas.upenn.edu/',
    expertName:  'Dr. Martin Seligman',
    expertTitle: 'Zellerbach Family Professor of Psychology, University of Pennsylvania',
    expertBio:   'Dr. Martin Seligman pioneered positive psychology and developed the PERMA model of wellbeing (Positive emotion, Engagement, Relationships, Meaning, Achievement). Former president of the American Psychological Association, he has authored over 20 books and hundreds of peer-reviewed articles on resilience, optimism, and human flourishing.',
    expertContactUrl: 'https://ppc.sas.upenn.edu/',
    description: 'Father of Positive Psychology whose PERMA framework and learned optimism research form the backbone of evidence-based resilience interventions worldwide. [Expert-informed]',
    excerpt:     'The father of positive psychology: his PERMA model and resilience research underpin most modern evidence-based wellbeing programs.',
    tags:        ['expert', 'positive-psychology', 'perma', 'seligman'],
    dimensions:  ['Cognitive-Narrative', 'Agentic-Generative', 'Spiritual-Reflective', 'Relational-Social'],
    timeCommitment: 5,
    status:      'published',
    publishedAt: new Date('2023-01-08'),
  },

  {
    title:       'The Science of Happiness: Greater Good Science Center Podcast',
    type:        'podcast',
    category:    'general',
    difficulty:  'beginner',
    url:         'https://greatergood.berkeley.edu/podcasts',
    description: 'Award-winning podcast from UC Berkeley\'s Greater Good Science Center exploring the science of resilience, happiness, compassion, and human flourishing. Hosts include researchers translating peer-reviewed studies into practical strategies. [Gov/Academic]',
    excerpt:     'UC Berkeley\'s award-winning podcast translating positive psychology and resilience science into everyday practice.',
    authorName:  'Greater Good Science Center, UC Berkeley',
    tags:        ['podcast', 'happiness', 'resilience', 'berkeley'],
    dimensions:  ['Cognitive-Narrative', 'Emotional-Somatic', 'Relational-Social'],
    timeCommitment: 45,
    status:      'published',
    publishedAt: new Date('2023-04-15'),
  },

  {
    title:       'ACT Made Simple: The Extra-Large Workbook',
    type:        'pdf',
    category:    'general',
    difficulty:  'intermediate',
    url:         'https://www.newharbinger.com/9781684038701/act-made-simple/',
    pdfUrl:      'https://www.newharbinger.com/9781684038701/act-made-simple/',
    description: 'Comprehensive ACT workbook by Dr. Russ Harris, one of the world\'s leading ACT trainers. Covers the six core ACT processes for building psychological flexibility and resilience, with exercises grounded in 500+ RCTs. [Peer-reviewed]',
    excerpt:     'Comprehensive ACT workbook covering all six core processes for building psychological flexibility and resilience.',
    authorName:  'Dr. Russ Harris',
    tags:        ['act', 'workbook', 'psychological-flexibility', 'resilience'],
    dimensions:  ['Cognitive-Narrative', 'Emotional-Somatic', 'Agentic-Generative', 'Spiritual-Reflective'],
    timeCommitment: 180,
    status:      'published',
    publishedAt: new Date('2023-02-20'),
  },

  {
    title:       'Three Strategies for Resilience: Dr. Lucy Hone TED Talk',
    type:        'video',
    category:    'general',
    difficulty:  'beginner',
    url:         'https://www.youtube.com/watch?v=NWH8N-BvhAw',
    videoProvider: 'youtube',
    videoId:     'NWH8N-BvhAw',
    description: 'TED Talk by Dr. Lucy Hone, resilience researcher at the New Zealand Institute of Wellbeing and Resilience, presenting three evidence-based strategies she personally applied after tragedy. Grounded in positive psychology research. [Expert-informed]',
    excerpt:     'Resilience researcher Lucy Hone shares three scientifically validated strategies for surviving adversity and trauma.',
    authorName:  'TED / Dr. Lucy Hone',
    tags:        ['ted', 'resilience', 'strategies', 'wellbeing'],
    dimensions:  ['Cognitive-Narrative', 'Emotional-Somatic', 'Spiritual-Reflective'],
    timeCommitment: 16,
    status:      'published',
    publishedAt: new Date('2023-03-01'),
  },

  {
    title:       'Brief Resilience Scale: Validated Self-Assessment',
    type:        'quiz',
    category:    'general',
    difficulty:  'beginner',
    url:         'https://www.psytoolkit.org/survey-library/resilience-BRS.html',
    description: 'Validated 6-item Brief Resilience Scale developed by Smith et al. (2008) in Health Psychology. Measures the ability to bounce back from adversity. Widely used in resilience research with strong psychometric properties across diverse populations. [Peer-reviewed]',
    excerpt:     'The gold-standard validated 6-item scale for measuring your capacity to bounce back from adversity.',
    authorName:  'Smith et al., Health Psychology (2008)',
    tags:        ['quiz', 'resilience', 'validated', 'scale', 'brs'],
    dimensions:  ['Cognitive-Narrative', 'Emotional-Somatic', 'Agentic-Generative'],
    timeCommitment: 5,
    status:      'published',
    publishedAt: new Date('2023-01-20'),
  },

  {
    title:       'Applied Behavior Analysis and Resilience: Behavioral Approaches to Wellbeing',
    type:        'article',
    category:    'general',
    difficulty:  'intermediate',
    url:         'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2846580/',
    description: 'Peer-reviewed article in Behavior Analysis in Practice examining Applied Behavior Analysis (ABA) principles in resilience building. Covers reinforcement schedules, behavioral activation, and skill-building approaches to psychological resilience. [Peer-reviewed]',
    excerpt:     'How Applied Behavior Analysis (ABA) principles provide evidence-based tools for building lasting psychological resilience.',
    authorName:  'NIH / Behavior Analysis in Practice',
    tags:        ['aba', 'behavior-analysis', 'resilience', 'peer-reviewed'],
    dimensions:  ['Agentic-Generative', 'Cognitive-Narrative'],
    timeCommitment: 20,
    status:      'published',
    publishedAt: new Date('2023-03-15'),
  },

];
