'use strict';

/**
 * ChildProfile.js — Mongoose model for IATLAS child profiles.
 *
 * Each document represents one child profile owned by a parent user.
 * Progress is stored as a nested sub-document so that a single GET
 * returns everything needed to restore a child's session.
 */

const mongoose = require('mongoose');

const progressSchema = new mongoose.Schema(
  {
    dimensions:          { type: Object,  default: {} },
    totalXP:             { type: Number,  default: 0  },
    level:               { type: Number,  default: 1  },
    badges:              { type: Array,   default: [] },
    streaks:             { type: Object,  default: {} },
    completedActivities: { type: Object,  default: {} },
    certificates:        { type: Array,   default: [] },
  },
  { _id: false }
);

// Clinical information sub-schema (all fields optional).
const clinicalSchema = new mongoose.Schema(
  {
    diagnoses:    { type: [String], default: [] },
    goals:        { type: [String], default: [] },
    strengths:    { type: String,   default: '' },
    challenges:   { type: String,   default: '' },
    supportLevel: {
      type: String,
      enum: ['low', 'moderate', 'high', 'intensive', ''],
      default: '',
    },
  },
  { _id: false }
);

// Preferences sub-schema (all fields optional).
const preferencesSchema = new mongoose.Schema(
  {
    activities:          { type: [String], default: [] },
    sensoryPreferences:  { type: String,   default: '' },
    communicationStyle:  { type: String,   default: '' },
    learningPreferences: { type: String,   default: '' },
  },
  { _id: false }
);

const childProfileSchema = new mongoose.Schema(
  {
    // UUID v4 generated by the client / route handler — used as the stable
    // external identifier instead of the MongoDB ObjectId.
    profileId: {
      type:     String,
      required: true,
      unique:   true,
      index:    true,
    },

    // Parent's Auth0 sub (or legacy userId) — foreign key into the users collection.
    userId: {
      type:     String,
      required: true,
      index:    true,
    },

    name: {
      type:      String,
      required:  true,
      trim:      true,
      maxlength: 64,
    },

    // One of the four IATLAS Kids age-group identifiers.
    ageGroup: {
      type: String,
      enum: ['5-7', '8-10', '11-14', '15-18', null],
    },

    // Child's date of birth (optional).
    dateOfBirth: {
      type: Date,
    },

    // Child's gender (optional).
    gender: {
      type: String,
      enum: ['male', 'female', 'non-binary', 'prefer-not-to-say', ''],
      default: '',
    },

    // URL or emoji string displayed as the child's avatar.
    avatar: {
      type:    String,
      default: '🧒',
    },

    // Clinical information (optional, populated in step 2 of profile wizard).
    clinical: {
      type:    clinicalSchema,
      default: () => ({}),
    },

    // Preferences (optional, populated in step 3 of profile wizard).
    preferences: {
      type:    preferencesSchema,
      default: () => ({}),
    },

    progress: {
      type:    progressSchema,
      default: () => ({}),
    },

    // Soft-delete flag.  Profiles are never hard-deleted so that progress data
    // is preserved for compliance / account-recovery purposes.
    archived: {
      type:    Boolean,
      default: false,
      index:   true,
    },

    // ── Progress Circle fields ────────────────────────────────────────────────

    // Reference to the ProgressCircle this profile is enrolled in (if any).
    progressCircleId: {
      type:    mongoose.Schema.Types.ObjectId,
      ref:     'ProgressCircle',
      default: null,
      index:   true,
    },

    // Privacy consent for team-sharing features.
    privacyConsent: {
      sharingEnabled:  { type: Boolean, default: false },
      consentedBy:     { type: mongoose.Schema.Types.ObjectId, ref: 'User', default: null },
      consentedAt:     { type: Date,   default: null },
      consentVersion:  { type: String, default: '1.0' },
    },

    // Activity log tracking who completed what activity, where, and when.
    activityLog: [
      {
        activityId:       { type: String,  required: true },
        completedAt:      { type: Date,    default: Date.now },
        completedBy:      { type: mongoose.Schema.Types.ObjectId, ref: 'User', default: null },
        completedByRole:  { type: String,  default: '' },
        setting:          { type: String,  default: '' },
        dimension:        { type: String,  default: '' },
        xpAwarded:        { type: Number,  default: 0 },
      },
    ],
  },
  { timestamps: true }
);

// Compound index so listing a user's active profiles is fast.
childProfileSchema.index({ userId: 1, archived: 1 });

module.exports = mongoose.model('ChildProfile', childProfileSchema);
