'use strict';

/**
 * ChildProfile.js — Mongoose model for IATLAS child profiles.
 *
 * Each document represents one child profile owned by a parent user.
 * Progress is stored as a nested sub-document so that a single GET
 * returns everything needed to restore a child's session.
 */

const mongoose = require('mongoose');

const progressSchema = new mongoose.Schema(
  {
    dimensions:          { type: Object,  default: {} },
    totalXP:             { type: Number,  default: 0  },
    level:               { type: Number,  default: 1  },
    badges:              { type: Array,   default: [] },
    streaks:             { type: Object,  default: {} },
    completedActivities: { type: Object,  default: {} },
  },
  { _id: false }
);

const childProfileSchema = new mongoose.Schema(
  {
    // UUID v4 generated by the client / route handler — used as the stable
    // external identifier instead of the MongoDB ObjectId.
    profileId: {
      type:     String,
      required: true,
      unique:   true,
      index:    true,
    },

    // Parent's Auth0 sub (or legacy userId) — foreign key into the users collection.
    userId: {
      type:     String,
      required: true,
      index:    true,
    },

    name: {
      type:      String,
      required:  true,
      trim:      true,
      maxlength: 64,
    },

    // One of the four IATLAS Kids age-group identifiers.
    ageGroup: {
      type: String,
      enum: ['5-7', '8-10', '11-14', '15-18'],
    },

    // URL or emoji string displayed as the child's avatar.
    avatar: {
      type:    String,
      default: '🧒',
    },

    progress: {
      type:    progressSchema,
      default: () => ({}),
    },

    // Soft-delete flag.  Profiles are never hard-deleted so that progress data
    // is preserved for compliance / account-recovery purposes.
    archived: {
      type:    Boolean,
      default: false,
      index:   true,
    },
  },
  { timestamps: true }
);

// Compound index so listing a user's active profiles is fast.
childProfileSchema.index({ userId: 1, archived: 1 });

module.exports = mongoose.model('ChildProfile', childProfileSchema);
