'use strict';

/**
 * SessionPlan.js — Mongoose model for IATLAS clinical session plans.
 *
 * Each document represents one session plan created by a practitioner.
 * Plans are soft-deleted via the `archived` flag so that historical data
 * is preserved for compliance purposes.
 */

const mongoose = require('mongoose');

// ── Sub-schemas ───────────────────────────────────────────────────────────────

const activitySelectedSchema = new mongoose.Schema(
  {
    type:      { type: String, enum: ['protocol', 'activity', 'custom'] },
    reference: { type: String, default: '' },
    title:     { type: String, required: true, trim: true },
    notes:     { type: String, default: '' },
  },
  { _id: false }
);

const dataCollectedSchema = new mongoose.Schema(
  {
    target:      { type: String, default: '' },
    measurement: { type: String, default: '' },
    value:       { type: String, default: '' },
    notes:       { type: String, default: '' },
  },
  { _id: false }
);

const progressObjectiveSchema = new mongoose.Schema(
  {
    objectiveId: { type: String, default: '' },
    trend: {
      type: String,
      enum: ['making-progress', 'flat', 'regression', 'mastered', ''],
      default: '',
    },
    notes: { type: String, default: '' },
  },
  { _id: false }
);

const homeworkSchema = new mongoose.Schema(
  {
    task:      { type: String, required: true, trim: true },
    due:       { type: Date,    default: null },
    completed: { type: Boolean, default: false },
  },
  { _id: false }
);

// ── Main schema ───────────────────────────────────────────────────────────────

const sessionPlanSchema = new mongoose.Schema(
  {
    // UUID v4 generated by the route handler — stable external identifier.
    sessionPlanId: {
      type:     String,
      required: true,
      unique:   true,
      index:    true,
    },

    // Auth0 sub of the practitioner who owns this plan.
    userId: {
      type:     String,
      required: true,
      index:    true,
    },

    // Client name or ID — NOT intended to store sensitive PII; practitioners
    // should use an anonymised identifier or initials.
    clientIdentifier: {
      type:     String,
      required: true,
      trim:     true,
      maxLength: 128,
    },

    sessionDate:   { type: Date,   default: null },
    sessionNumber: { type: Number, default: null },

    dimensionalFocus: {
      type: String,
      enum: [
        'agentic-generative',
        'somatic-regulative',
        'cognitive-interpretive',
        'emotional-adaptive',
        'relational-integrative',
        'spiritual-existential',
        '',
      ],
      default: '',
    },

    sessionGoals:              { type: [String],                  default: [] },
    activitiesSelected:        { type: [activitySelectedSchema],  default: [] },
    sessionNotes:              { type: String,                    default: '' },
    dataCollected:             { type: [dataCollectedSchema],     default: [] },
    progressTowardObjectives:  { type: [progressObjectiveSchema], default: [] },
    generalizationObserved:    { type: String,                    default: '' },
    homeworkAssigned:          { type: [homeworkSchema],          default: [] },
    planForNextSession:        { type: String,                    default: '' },
    clinicalNotes:             { type: String,                    default: '' },

    // Soft-delete flag.
    archived: {
      type:    Boolean,
      default: false,
      index:   true,
    },
  },
  { timestamps: true }
);

// Compound index for listing a user's active plans efficiently.
sessionPlanSchema.index({ userId: 1, archived: 1, sessionDate: -1 });

module.exports = mongoose.model('SessionPlan', sessionPlanSchema);
