#!/usr/bin/env bash
# setup_atlas_bashrc.sh
#
# Complete setup script for the Resilience Atlas development environment.
# Backs up the existing ~/.bashrc and creates a new one containing the
# atlas() launcher function plus standard bash settings.
#
# Usage:
#   bash scripts/setup_atlas_bashrc.sh
#
# After running, reload your shell:
#   source ~/.bashrc

set -euo pipefail

BASHRC="$HOME/.bashrc"
BACKUP="$HOME/.bashrc.bak.$(date +%Y%m%d%H%M%S)"

# ---------------------------------------------------------------------------
# Helper
# ---------------------------------------------------------------------------
info()    { printf '\033[0;34m[INFO]\033[0m  %s\n' "$*"; }
success() { printf '\033[0;32m[OK]\033[0m    %s\n' "$*"; }
warn()    { printf '\033[0;33m[WARN]\033[0m  %s\n' "$*"; }

# ---------------------------------------------------------------------------
# 1. Back up existing .bashrc
# ---------------------------------------------------------------------------
if [[ -f "$BASHRC" ]]; then
    cp "$BASHRC" "$BACKUP"
    info "Existing ~/.bashrc backed up to: $BACKUP"
fi

# ---------------------------------------------------------------------------
# 2. Write new .bashrc (Unix line endings guaranteed by this script)
# ---------------------------------------------------------------------------
cat > "$BASHRC" << 'BASHRC_EOF'
# ~/.bashrc — generated by setup_atlas_bashrc.sh

# ── Standard bash settings ─────────────────────────────────────────────────

# Enable programmable completion
if ! shopt -oq posix; then
    if [[ -f /usr/share/bash-completion/bash_completion ]]; then
        . /usr/share/bash-completion/bash_completion
    elif [[ -f /etc/bash_completion ]]; then
        . /etc/bash_completion
    fi
fi

# npm global bin on PATH
if command -v npm &>/dev/null; then
    NPM_GLOBAL_BIN="$(npm root -g 2>/dev/null)/../bin"
    [[ -d "$NPM_GLOBAL_BIN" ]] && export PATH="$PATH:$NPM_GLOBAL_BIN"
fi

# History settings
HISTSIZE=10000
HISTFILESIZE=20000
HISTCONTROL=ignoreboth
shopt -s histappend

# ── atlas() launcher ────────────────────────────────────────────────────────

atlas() {
    local port=3000
    local max_port=3099

    # Find the first available port starting from 3000.
    # Both ss and netstat output :<port> followed by a space, tab, or newline,
    # so we match :<port> followed by a non-digit to avoid false positives like
    # :30001 when checking for 3000.
    while [[ $port -le $max_port ]]; do
        if ! ss -ltn 2>/dev/null | grep -qE ":${port}[^0-9]" && \
           ! netstat -ltn 2>/dev/null | grep -qE ":${port}[^0-9]"; then
            break
        fi
        port=$((port + 1))
    done

    if [[ $port -gt $max_port ]]; then
        printf '\033[0;31m[ERROR]\033[0m No free port found in range 3000-%s.\n' "$max_port" >&2
        return 1
    fi

    if [[ $port -ne 3000 ]]; then
        printf '\033[0;33m[WARN]\033[0m  Port 3000 is in use. Using port %s instead.\n' "$port"
    fi

    # Locate the repository root (directory containing backend/server.js)
    local repo_root
    if [[ -f "$(pwd)/backend/server.js" ]]; then
        repo_root="$(pwd)"
    elif [[ -n "${ATLAS_ROOT:-}" && -f "$ATLAS_ROOT/backend/server.js" ]]; then
        repo_root="$ATLAS_ROOT"
    else
        printf '\033[0;31m[ERROR]\033[0m Cannot find the Resilience Atlas repository.\n' >&2
        printf '        Run this command from the repository root, or set ATLAS_ROOT.\n' >&2
        return 1
    fi

    # Check that nodemon is available
    if ! command -v nodemon &>/dev/null; then
        printf '\033[0;31m[ERROR]\033[0m nodemon is not installed. Run: npm install -g nodemon\n' >&2
        return 1
    fi

    printf '\033[0;34m[INFO]\033[0m  Starting Resilience Atlas on port %s ...\n' "$port"

    # Start the server in the background with the chosen port
    PORT="$port" nodemon "$repo_root/backend/server.js" &
    local server_pid=$!

    # Wait for the server to be ready (poll with curl, timeout after 30 s)
    local url="http://localhost:${port}"
    local waited=0
    printf '\033[0;34m[INFO]\033[0m  Waiting for server to become ready'
    until curl -s --max-time 1 "$url" >/dev/null 2>&1; do
        if [[ $waited -ge 30 ]]; then
            printf '\n'
            printf '\033[0;33m[WARN]\033[0m  Server did not respond within 30 s. Opening browser anyway.\n'
            break
        fi
        printf '.'
        sleep 1
        waited=$((waited + 1))
    done
    printf '\n'

    # Open the browser — WSL / Windows integration
    if grep -qi microsoft /proc/version 2>/dev/null; then
        # Running inside WSL — open with the Windows default browser
        if command -v wslview &>/dev/null; then
            wslview "$url"
        elif command -v cmd.exe &>/dev/null; then
            cmd.exe /c start "" "$url"
        else
            printf '\033[0;33m[WARN]\033[0m  Cannot detect WSL browser helper. Open manually: %s\n' "$url"
        fi
    elif command -v xdg-open &>/dev/null; then
        xdg-open "$url"
    elif command -v open &>/dev/null; then
        open "$url"
    else
        printf '\033[0;33m[WARN]\033[0m  No browser opener found. Open manually: %s\n' "$url"
    fi

    printf '\033[0;32m[OK]\033[0m    Server running (PID %s). Press Ctrl+C to stop.\n' "$server_pid"
    wait "$server_pid"
}
BASHRC_EOF

# Ensure Unix line endings (convert CRLF → LF) in case the script itself was
# checked out on Windows.
if command -v sed &>/dev/null; then
    sed -i 's/\r$//' "$BASHRC"
fi

success "New ~/.bashrc written successfully."
info    "Reload your shell with:  source ~/.bashrc"
info    "Start the app with:      atlas"
