name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set up Environment
        run: | 
          # setup tasks

      - name: Run Tests
        run: | 
          echo "Running tests..."

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Deploy to Staging
        env:
          RAILWAY_SERVICE: ${{ secrets.RAILWAY_SERVICE }}
        run: railway up --service ${{ env.RAILWAY_SERVICE }} --environment Staging
